apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-deployment
  namespace: karsajobs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: karsajobs
  template:
    metadata:
      labels:
        app: karsajobs
    spec:
      containers:
        - name: karsajobs
          image: ghcr.io/agung-parama/karsajobs/karsajobs-be:latest
          ports:
            - containerPort: 8080
          env:
            - name: APP_PORT
              value: "8080"
            - name: MONGO_HOST
              value: "http://mongo-service.karsajobs.svc.cluster.local:27017"
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_ROOT_USERNAME
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_ROOT_PASSWORD
